#!/usr/bin/env bash

#
# brew-requires
#

req="$(brew uses --installed --skip-recommended "$1" | sort)"
build="$(comm -1 -3 <(printf "$req\n") <(brew uses --installed --include-build --skip-recommended "$1" | sort))"
if [[ -z "$req" && -z "$build" ]]; then
  printf "\e[1;38;5;9m$1\e[0m is not required by any installed formulae.\n"
else
  if [[ -n "$req" ]]; then
    printf "\e[1;38;5;9mRequired:\e[0m\n$req\n"
  fi
  if [[ -n "$build" ]]; then
    printf "\e[1;38;5;9mBuild:\e[0m\n$build\n"
  fi
fi

