#!/usr/bin/env bash

#
# brew-requires
#

declare -a required=($(brew uses --installed --skip-recommended $1))
declare -a uses=($(brew uses --installed $1))
for i in "${uses[@]}"; do
  if [[ " ${required[@]} " =~ " $i " ]]; then
    printf "\e[1;38;5;15m$i -\e[0m \e[1;38;5;9mRequired\e[0m\n"
  else
    printf "\e[1;38;5;15m$i -\e[0m \e[1;38;5;9mRecommended\e[0m\n"
  fi
done
