#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
  branch=$(git rev-parse --abbrev-ref HEAD)
else
  branch=$1
fi
parent=$(git show-branch | sed "s/].*//" | grep "\*" | grep -v "$branch" | head -n1 | sed "s/^.*\[//")
commit=$(diff -u <(git rev-list --first-parent $branch) <(git rev-list --first-parent origin/master) | sed -ne 's/^ //p' | head -1)
commit=${commit:0:7}
echo "The immediate parent branch of $branch is: $(tput setaf 220)$parent$(tput sgr0)"
echo "The base commit of $branch is:             $(tput setaf 220)$commit$(tput sgr0)"

