#!/usr/bin/env bash

#
# git-unstage
#

if [[ $# -eq 0 ]]; then
  echo "Usage: git unstage <file>..."
else
  if ! [[ -z "$(git show-ref --head)" ]]; then
    git reset HEAD $(git list $@ | sed "s/"$'\E\[1;31m'"//g") > /dev/null
  else
    git rm -r --cached  $(git list $@ | sed "s/"$'\E\[1;31m'"//g") > /dev/null
  fi
  git number | sed '/(use "git /d' | sed '/^$/d' | sed 1,2d
  echo
fi

