#!/usr/bin/env bash

#
# git-discard
#

if [[ $# -eq 0 ]]; then
  printf "Usage: git discard <file>...\n"
else
  files=""
  for i in "$@"; do
    files=$(git list $i | sed "s/"$'\E\[1;31m'"//g")" $files"
  done
  if [[ -n "$files" ]]; then
    printf "Discarding changes to: $files\n"
    git checkout -- $files
  fi
  git number | sed '/(use "git /d' | sed '/^$/d' | sed 1,2d
fi

