#!/usr/bin/env bash

set -euo pipefail

#
# install everything
#

# get Homebrew
if ! command -v brew &>/dev/null; then
  if [[ "$(uname)" == 'Linux' ]]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
    /home/linuxbrew/.linuxbrew/bin/brew bundle install
    /home/linuxbrew/.linuxbrew/bin/brew/opt/fzf/install
  else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    brew bundle install
  fi
fi

# symlink stuff
stow --no-folding --restow config -t "$HOME"

# install tpm
[[ ! -d ~/.tmux/plugins/tpm ]] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# make directory for personal repos
mkdir -p "$HOME/src/chriskim06"

# create empty file for secrets/tokens and local aliases
touch "$HOME/.private"
