#!/usr/bin/env bash

set -e

# Create directories if they don't exist
[[ ! -d ~/.vim/config ]] && mkdir -p ~/.vim/config
[[ ! -d ~/.vim/bundle ]] && mkdir -p ~/.vim/bundle
[[ ! -d ~/.vim/after/ftplugin ]] && mkdir -p ~/.vim/after/ftplugin
[[ ! -d ~/.vim/autoload ]] && mkdir -p ~/.vim/autoload
[[ ! -d ~/.config/nvim ]] && mkdir -p ~/.config/nvim

# Symlink files into proper places
CWD=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ln -sf $CWD/.vimrc ~
ln -sf $CWD/init.vim ~/.config/nvim
ln -sf $CWD/config/* ~/.vim/config
ln -sf $CWD/after/ftplugin/* ~/.vim/after/ftplugin
ln -sf $CWD/coc-settings.json ~/.config/nvim

# Install stuff
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +'PlugInstall --sync' +qa

# Try moving onedark theme to vim-airline-themes
airline="$HOME/.vim/bundle/vim-airline-themes/autoload/airline/themes"
[[ -d $airline ]] && ln -sf $CWD/onedark.vim $airline
