#!/usr/bin/env bash

#
# Custom git completion functions
#

_git_completion () {
  local cur prev
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD - 1]}
  COMPREPLY=()
  case "$prev" in
    g|git)
      local gitcmds="$(__git_list_all_commands | grep -ve '--\|cvs\|mail\|arch\|[merge\|remote\|unpack\|update\|upload\|verify]-')"
      COMPREPLY=($(compgen -W "$gitcmds $(__git_aliases) --help" -- ${cur}))
      ;;
    *)
      local al cmd
      al="$(__git_aliased_command ${COMP_WORDS[1]})"
      if ! [[ -z "$al" ]]; then
        cmd="$(echo "_git_$al" | tr '-' '_')"
      else
        cmd="$(echo "_git_${COMP_WORDS[1]}" | tr '-' '_')"
      fi
      if [[ "$(type -t $cmd)" == "function" ]]; then
        $cmd
      else
        COMPREPLY+=($(compgen -W "--help $(ls)" -- ${cur}))
      fi
      ;;
  esac
}

_git_number () {
  __gitcomp "$(__git_list_all_commands && __git_aliases)"
}

_git_ignore () {
  __gitcomp "$(git ignore -L)"
}

_git_unstage () {
  __gitcomp "$(git diff --name-only --cached)"
}

_git_delete () {
  __gitcomp "$(git diff --name-only)"
}

_git_discard () {
  __gitcomp "$(git status --porcelain | cut -c4-)"
}

_git_sync () {
  __gitcomp "$(git branch)"
}

