#!/usr/bin/env bash

#
# git-squash
#

__print_squash_usage() {
  printf "Usage: git squash [amount|commit]\n"
  printf "\tamount - number of commits to squash starting from HEAD (greater than 0)\n"
  printf "\tcommit - hash before commits to be squashed (hash length must be at least 7)\n"
}

if [[ $# -eq 1 ]]; then
  if [[ "$1" =~ ^[A-Za-z0-9]{7,}$ ]]; then
    git reset --soft $1 && git commit --edit -m "$(git log --format=%B --reverse HEAD..HEAD@{1})"
  elif [[ $1 -gt 0 ]] 2>/dev/null; then
    git reset --soft HEAD~$1 && git commit --edit -m "$(git log --format=%B --reverse HEAD..HEAD@{1})"
  else
    __print_squash_usage
  fi
  exit 0
fi
__print_squash_usage
