#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 2 ]]; then
  printf "Usage: git view <revision> <file>\n"
  exit 1
fi

files=($(git ls-tree -r HEAD --name-only | grep "$2"))
count=${#files[@]}
if [[ $count -eq 1 ]]; then
  git show "$1:${files[0]}"
else
  printf "Choose a file to view by entering its number:\n"
  for ((i = 0; i < $count; i++)); do
    printf "  $((i + 1)): ${files[i]}\n"
  done

  read -e -r -p "> " choice
  if [[ $((choice)) != $choice ]]; then
    printf "Must input a number!\n\n"
    exit 1
  fi

  file=${files[$choice]}
  if [[ -z "$file" ]]; then
    printf "Choose a number within the given range!\n\n"
    exit 1
  fi
  git show "$1:$file"
fi
